language: python
sudo: false

python:
  - "3.4"
  - "3.5"

before_install:
  # use latest because why not?
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda config --set always_yes true
  - conda update conda
  # pin to numpy < 1.10 because pandas 0.16 and numpy 1.10 do not play nice
  - conda create -n testenv pip python=$TRAVIS_PYTHON_VERSION six "numpy<1.10" pandas h5py coverage jsonschema jinja2 sphinx
  - source activate testenv
  # deps needed for metadatastore/filestore
  - conda install -n testenv pyyaml ipywidgets 
  # Dependencies not in official conda have been uploaded to binstar orgs.
  - conda config --add channels lightsource2
  - conda install mongoengine tzlocal prettytable boltons pymongo=2.9 pims tifffile
  - conda install databroker
  - conda config --add channels bokeh
  - conda install sphinx-bootstrap-theme
  # install all the pip deps
  - pip install coveralls
  - pip install codecov
  - pip install travis-sphinx
  - python setup.py install

script:
  - coverage run --source=csxtools setup.py test
  - cd $TRAVIS_BUILD_DIR/docs
  - make html
  - cd $TRAVIS_BUILD_DIR

after_success:
  - coveralls
  - codecov
  - cd $TRAVIS_BUILD_DIR/docs
  - make gh_pages
# Note the following command sets a new directory
