language: python
sudo: false

matrix:
    include:
        - python: 3.5
      
services:
    - mongodb

addons:
  apt:
    sources:
        - mongodb-3.2-precise
    packages:
        - mongodb-org-server
        - mongodb-org

env:
    global:
        - GH_USER=stuwilkins
        - MDS_HOST=localhost
        - MDS_DATABASE=test
        - MDS_TIMEZONE=US/Eastern
        - FS_HOST=localhost
        - FS_DATABASE=test

before_install:
    - git config --global user.email "donotreply@travis.ci"
    - git config --global user.name "travisci"
    - git config --global credential.helper store --file=$HOME/.git-credentials
    - echo "https://${GH_USER}:${GH_TOKEN}@github.com" > $HOME/.git-credentials
    - git clone https://github.com/nsls-ii/nsls2-ci ~/ci_scripts
    - . ~/ci_scripts/install-miniconda.sh
    - . ~/ci_scripts/init-filestore.sh
    - . ~/ci_scripts/init-metadatastore.sh

install:
    - export GIT_FULL_HASH=`git rev-parse HEAD`
    - conda config --show
    - conda create -n testenv pytest cytoolz pandas ujson six jsonschema doct h5py tornado pymongo pytz numpy tifffile jinja2 coverage pyyaml tzlocal nose python=$TRAVIS_PYTHON_VERSION pims prettytable pip boltons requests databroker sphinx sphinx-bootstrap-theme pandoc ipython nbconvert jupyter  -c lightsource2-tag -c conda-forge
    - source activate testenv
    - pip install -r requirements-dev.txt
    - python setup.py install build_ext -i

script:
    - flake8
    - coverage run --source=csxtools run_tests.py
    - cd $TRAVIS_BUILD_DIR/doc && make html
    #- cd $TRAVIS_BUILD_DIR && conda build conda-recipe
    
after_success:
    - cd $TRAVIS_BUILD_DIR && coveralls
    - cd $TRAVIS_BUILD_DIR && codecov
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      cd $TRAVIS_BUILD_DIR/doc && make gh-pages; fi;

