notifications:
    email:
        on_success: always
        on_failure: always
language: python
sudo: false
python:
  - "3.5"
install:
  - pip install coverage
  - python setup.py install
script:
  - python setup.py test
after_success:
  - coveralls
