language: python
sudo: false

matrix:
    include:
        - python: 3.5
      
services:
    - mongodb

addons:
  apt:
    sources:
        - mongodb-3.2-precise
    packages:
        - mongodb-org-server
        - mongodb-org

env:
    global:
        - GH_USER=stuwilkins
        - MDS_HOST=localhost
        - MDS_DATABASE=test
        - MDS_TIMEZONE=US/Eastern
        - FS_HOST=localhost
        - FS_DATABASE=test

before_install:
    - git config --global user.email "donotreply@travis.ci"
    - git config --global user.name "travisci"
    - git config --global credential.helper store --file=$HOME/.git-credentials
    - echo "https://${GH_USER}:${GH_TOKEN}@github.com" > $HOME/.git-credentials

install:
    - export GIT_FULL_HASH=`git rev-parse HEAD`
    - pip install --upgrade numpy setuptools pip
    - pip install -r requirements-dev.txt
    - pip install -e .[complete]

script:
    - flake8
    - coverage run --source=csxtools run_tests.py
    - cd $TRAVIS_BUILD_DIR/doc && make html
    
after_success:
    - cd $TRAVIS_BUILD_DIR && coveralls
    - cd $TRAVIS_BUILD_DIR && codecov
    - |
      if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
        cd $TRAVIS_BUILD_DIR/doc && make gh-pages
      fi
