language: python
sudo: false
python:
- '3.5'
before_install:
# Setup git config for using tokens
- git config --global user.email "donotreply@travis.ci"
- git config --global user.name "travisci"
- git config --global credential.helper store --file=$HOME/.git-credentials
- echo "https://${GH_USER}:${GH_TOKEN}@github.com" > $HOME/.git-credentials
# Install miniconda
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- chmod +x miniconda.sh
- "./miniconda.sh -b -p /home/travis/mc"
- export PATH=/home/travis/mc/bin:$PATH
# Set up config for MDS and FS.
- mkdir -p /home/travis/.config/metadatastore
- echo "port: 27017" > /home/travis/.config/metadatastore/connection.yml
- mkdir -p /home/travis/.config/filestore
- echo "port: 27017" > /home/travis/.config/filestore/connection.yml
install:
- export GIT_FULL_HASH=`git rev-parse HEAD`
- conda config --set always_yes true
- conda update conda
- conda create -n testenv pip python=$TRAVIS_PYTHON_VERSION six "numpy<1.10" pandas
  h5py coverage jsonschema jinja2 sphinx
- source activate testenv
- conda install -n testenv pyyaml ipywidgets
- conda config --add channels lightsource2
- conda install mongoengine tzlocal prettytable boltons pymongo=2.9 pims tifffile
- conda install databroker
- conda config --add channels bokeh
- conda install sphinx-bootstrap-theme
- pip install coveralls
- pip install codecov
- python setup.py install
script:
- coverage run --source=csxtools setup.py test
- cd $TRAVIS_BUILD_DIR/docs && make html
after_success:
- cd $TRAVIS_BUILD_DIR && coveralls
- cd $TRAVIS_BUILD_DIR && codecov
#- [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ] && (cd $TRAVIS_BUILD_DIR/docs && make gh-pages)
env:
  global:
   - GH_USER=stuwilkins
   - MDS_HOST=localhost
   - MDS_DATABASE=test
   - MDS_TIMEZONE=US/Eastern
   - FS_HOST=localhost
   - FS_DATABASE=test
   - secure: jdgtHDA4Xo1L/WDBoA55xOaRi9TRYa2xX+QNPiYnyTQDADkJOD2noF/UlAHGs3rpnMOKSzg+TIl4XHgZ7vUJhcpq0BA+jdVgCg/Lop9Yev/BQSdFSv1f3LP1oZ5VDxl3YerG9wSb2ITiRznNCFnCxZiyBbbxdlZSwktsh2dCr6wks3LFRUME61eJhyRBpNfYL9tStTQUwfaRB8n/vV6vH6SKEhfyBdZf7pSHd3+YMteaEUdSAqQul6lTfZlvkPTUSkmR8NF51iKfqGkHp0RSgWam0pk0OSYQphSXB5aKqn5fJ/aMyh3iBrdYn9/hmx1VzNqjRvDBYyv1juVfcQuPcwir79wPuJO6DYi0dMyIuY/ObwzkFzjHK0BcVguSVeeSwUqd8sgZPiQ4xzAaGLNIhaf28YRdvnqtEMejRZFHLjOblpPo9drnemaS60n3ziKHEuYthB9JDKvZQQSAHPyIZugiNlgdLxcfT/RiJsQUIFEEqGlKeT2vP4oCwKtm6FWGrrlWVaX1dRGYecLSQyj8OLal1bBOjlvdnOZLUZFJkKbD4g2nq4EMZjV0GTMNtuVcDhAOLd82Ex0GB/8iyCWjJdfsEYFIzMe/s3uMopI5qI/0GT5GTfSqs/9kGov4Va48doyeFEht7ZbAkGBka8rbBjcyCjU1gyuy7x+QM5Sck8Y=
