language: python
sudo: false
python:
- '3.5'
before_install:
- git config --global user.email "donotreply@travis.ci"
- git config --global user.name "travisci"
- git config --global credential.helper store --file=$HOME/.git-credentials
- echo "https://${GH_USER}:${GH_TOKEN}@github.com" > $HOME/.git-credentials
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- chmod +x miniconda.sh
- "./miniconda.sh -b -p /home/travis/mc"
- export PATH=/home/travis/mc/bin:$PATH
- mkdir -p /home/travis/.config/metadatastore
- 'echo "port: 27017" > /home/travis/.config/metadatastore/connection.yml'
- mkdir -p /home/travis/.config/filestore
- 'echo "port: 27017" > /home/travis/.config/filestore/connection.yml'
install:
- export GIT_FULL_HASH=`git rev-parse HEAD`
- conda config --set always_yes true
- conda config --set show_channel_urls true
- conda config --add channels lightsource2
- conda config --add channels bokeh
- conda config --add channels asmeurer
- conda update conda
- conda install conda-build
- conda create -n testenv pip python=$TRAVIS_PYTHON_VERSION six "numpy<1.10" pandas
  h5py coverage jsonschema jinja2 sphinx pyyaml ipywidgets tzlocal prettytable boltons
  pymongo=2.9 pims tifffile databroker sphinx-bootstrap-theme pandoc
- source activate testenv
- ln -s /home/travis/mc/envs/testenv/lib/libgmp.so.10 /home/travis/mc/envs/testenv/lib/libgmp.so.3
- pip install coveralls
- pip install codecov
- pip install pytest-pep8
- python setup.py install build_ext -i
script:
- py.test --pep8 -m pep8
- coverage run --source=csxtools run_tests.py
- cd $TRAVIS_BUILD_DIR/doc && make html
after_success:
- cd $TRAVIS_BUILD_DIR && coveralls
- cd $TRAVIS_BUILD_DIR && codecov
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  cd $TRAVIS_BUILD_DIR/doc && make gh-pages; fi;
env:
  global:
  - GH_USER=stuwilkins
  - MDS_HOST=localhost
  - MDS_DATABASE=test
  - MDS_TIMEZONE=US/Eastern
  - FS_HOST=localhost
  - FS_DATABASE=test
  - secure: RnXoaYeEEu4oa5m+c/PYrR9KL71+tNHxoZLBq2iCIw5YJbYxpqS2qTIT0A8fTlZudgYYUMTWaBtPcyyafC2mqIdADzcOr5rU1S726uQfHWCkZG2CRbRvWriHDvck99MIQ36ePbSpZ3T7/HoiqHbpp80XrUDMii2cu8ovZ1icXWq8g8ZrThE4QiUmW/fNzY5n1bkshRYyed0n2qT1dtYSyI19VNI/CQ2G2KSjd1145TfOe04LSHqUHuCO0jkrBHVcvclhEF4FpJYGVq5adf8XuYOVkR+vEbIJyrhBJD9bfnPecq91gSyteLD5UR4XTZd45FkFfjz4Fe1cry4jF3tEZlXFhzQ2sQlSzvza8VtBqR+wqeh4tbFOiLOAdfUWa/GzjF7N11gYBeieSvwrXxT8anYYFJ31Q54yezEBaaGKJAUogRezoh9KyksZZ0ui3iUQ2LU+MPuWj4WsEhzWH9NhWsbQ8l17UAoa7DabkkHVFGGaaziRhnuo9NE/iX3CHOy3tOKvuaekLxI8JbArUPxQaFJ8nlofOKc33tULDwrCAP5kW1WQhcSqv+IdMvUixuS31EI2RFaOPqvd2sNLGk+WyhB3a3e8lJs+iUUpW5sOitD7hfQwsZVTMSsSHr2wOY87gPM+ag+9W8ZuOUbc/8Jf3pgHorchGYZJ4/BOLwQR5xQ=
