[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
    "numpy",
    "versioneer[toml]>=0.28"
]
build-backend = "setuptools.build_meta"
[tool.ruff]
exclude = [
    "examples",
    "doc",
    "build",
    "dist",
    "csxtools.egg-info",
    "__pycache__"
]
