#!/bin/bash

if [ -n "${GH_TOKEN}" ]; then
	echo "Using GH_TOKEN for authentication"
	git config credential.helper store --file=$HOME/.git-credentials
	echo "https://${GH_TOKEN}@github.com" > $HOME/.git-credentials
	cat $HOME/.git-credentials
	cat $HOME/.gitconfig
	git config --global user.email "donotreply@travis.ci"
	git config --global user.name "stuwilkins"
	git config --get remote.origin.url
fi

make gh-pages
