name: Unit Tests in NSLS-II Conda Environments

on: [push, pull_request, workflow_dispatch]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:

  matrix_prep:

    runs-on: ubuntu-latest
    outputs:
      matrix_include: ${{ steps.set-matrix.outputs.matrix_include }}
    steps:
    - name: Check out the code repo
      uses: actions/checkout@v4
    - name: Install python interpreter
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        set -vxeuo pipefail
        python -m pip install pyyaml
    - name: Import matrix.include from config file
      id: set-matrix
      run: |
        set -vxeuo pipefail
        export MATRIX_INCLUDE_DIR=${{ github.workspace }}/.github/conda-env-tests
        export MATRIX_INCLUDE_FILE=${MATRIX_INCLUDE_DIR}/recent-envs.yml
        echo "Building matrix from file ${MATRIX_INCLUDE_FILE}"
        export MATRIX_INCLUDE_SCRIPT=${MATRIX_INCLUDE_DIR}/matrix_include.py
        echo "matrix_include=$(python ${MATRIX_INCLUDE_SCRIPT})" >> $GITHUB_OUTPUT

  test-in-conda-env:
  
    needs: matrix_prep
    runs-on: ubuntu-latest
    steps:
    - name: Debug
      run: |
        echo ${{ env.BRANCH_NAME }}
    # - name: Check out the code repo
    #   uses: actions/checkout@v4
    # - name: Dispatch the test
    #   uses: ./.github/actions/test-in-conda-env.yml@${{env.BRANCH_NAME}}
    #   with:
    #     matrix_include: ${{ fromJson(needs.matrix_prep.outputs.matrix_include) }}
