name: Unit Tests in NSLS-II Conda Environments

on: [push, pull_request, workflow_dispatch]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:

  matrix_prep:

    runs-on: ubuntu-latest
    outputs:
      matrix_include: ${{ steps.set-matrix.outputs.matrix_include }}
    steps:
    - name: Check out the code repo
      uses: actions/checkout@v4
    - name: Install python interpreter
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        set -vxeuo pipefail
        python -m pip install pyyaml
    - name: Import matrix.include from config file
      id: set-matrix
      run: |
        set -vxeuo pipefail
        export MATRIX_INCLUDE_DIR=${{ github.workspace }}/.github/conda-env-tests
        export MATRIX_INCLUDE_FILE=${MATRIX_INCLUDE_DIR}/recent-envs.yml
        echo "Building matrix from file ${MATRIX_INCLUDE_FILE}"
        export MATRIX_INCLUDE_SCRIPT=${MATRIX_INCLUDE_DIR}/matrix_include.py
        echo "matrix_include=$(python ${MATRIX_INCLUDE_SCRIPT})" >> $GITHUB_OUTPUT

  test-in-conda-env:
  
    needs: matrix_prep
    uses: ./.github/workflows/_test-in-conda-env.yml
    with:
      conda_env_name: ${{ matrix.conda_env_name }}
      zenodo_id: ${{ matrix.zenodo_id }}
      md5_checksum: ${{ matrix.md5_checksum }}
      python-version: ${{ matrix.python-version }}
    strategy:
      max-parallel: 4
      matrix:
        include: ${{ fromJson(needs.matrix_prep.outputs.matrix_include) }}
      fail-fast: false
